### ISSUE TITLE
Redundancies Tool

### ISSUE THREAD

**Issue by yokoffing** [stephenhawk8054/PrivacyExtended#2]
### Part 1
[This](https://abpvn.com/ruleChecker/redundantRuleChecker.html) is a tool to help you filter redundancies. It's originally for AdBlock Plus and probably a little dated, so ignore the `warnings` tab when you're finished.

Running your list by itself, I get [1506 redundancies](https://bin.nixnet.services/?a8ee988d17806efe#3PBQsgDPD5BAdb8VnTTBFZUhGZ8pPehSF4bSUnjtKbtZ). Clicking on the `corrected` tab will give you list with all the duplicates removed: [Privacy Extended with redundancies removed](https://bin.nixnet.services/?64384a6be73eddb2#AT7c6rtBY9xuTjkz5YyBYZAmPjniyiounQtfy1XoxPLD)

### Part 2

Then I added EasyPrivacy + [your list w/ internal redundancies removed](https://bin.nixnet.services/?64384a6be73eddb2#AT7c6rtBY9xuTjkz5YyBYZAmPjniyiounQtfy1XoxPLD) to the tool. I listed EasyPrivacy first so that the first instance of a rule is left in EasyPrivacy but removed in your list (i.e., duplicate is removed in your list). This yielded [1648 redundancies](https://bin.nixnet.services/?7a937da32dfc8372#6LTp3TDpVitgVmmegpDwdSDwgufnZo5Vi6CDGQVz7YWU) removed total; 1148 redundancies were removed from your list specifically.

This gives the final corrected list: [Privacy Extended after removing internal duplicates and redundancies with EasyPrivacy](https://bin.nixnet.services/?14b84e32ed23983c#2ZkuKWduXWREVaEFhxE5JcyGBNTDRyZhh5wMTgrNqSvi). Here's the [raw](https://bin.nixnet.services/?14b84e32ed23983c#2ZkuKWduXWREVaEFhxE5JcyGBNTDRyZhh5wMTgrNqSvi) for copy+paste. I will go ahead and open a pull request #3.

**Comment by stephenhawk8054** [comment]
Thank you. Your PR is merged now.
