### ISSUE TITLE
`apple.com/metrics/` breaks livestream

### ISSUE THREAD

**Issue by yokoffing** [stephenhawk8054/PrivacyExtended#5]
``apple.com/metrics/`` breaks playing the stream on https://www.apple.com/apple-events/event-stream/.

Using `@@||apple.com/metrics/` allowed me to view the live stream on Chrome and Firefox.

https://github.com/AdguardTeam/AdguardFilters/issues/152894

**Comment by stephenhawk8054** [comment]
Thanks, although the livestream is off now, the site `https://www.apple.com/apple-events/` is broken with `||apple.com/metrics/`. Allowing this script makes it work for me, without the need to allow other `apple.com/metrics` connections

```adb
@@||apple.com/metrics/ac-analytics/*/scripts/ac-analytics.js$script,1p
```
